@baseUrl=http://localhost:3000

### get all acara
GET {{baseUrl}}/api/acara

### get one acara
GET {{baseUrl}}/api/acara/Zx7J8JUOXWVRpfC2j5MZ

### add data acara
POST {{baseUrl}}/api/acara
Content-Type: application/json

{
  "title": "Lomba Karya Tulis Ilmiah Nasional",
  "desc": "Kompetisi nasional untuk mahasiswa dalam penulisan karya ilmiah.",
  "prodi": "Teknik Geologi",
  "schedule": {
    "start_time": "2024-12-10T10:00:00Z",
    "end_time": "2024-12-12T15:00:00Z"
  },
  "rundown": [
    {
      "time": {
        "start": "2024-12-10T10:00:00Z",
        "end": "2024-12-10T12:00:00Z"
      },
      "session": "Technical Meeting",
      "speaker": "Panitia Lomba"
    },
    {
      "time": {
        "start": "2024-12-12T09:00:00Z",
        "end": "2024-12-12T15:00:00Z"
      },
      "session": "Presentasi Finalis",
      "speaker": "Tim Juri"
    }
  ],
  "status": "ongoing",
  "posters": ["poster2.jpg", "poster3.jpg"],
  "location": {
    "address": "Gedung Serbaguna, Universitas XYZ",
    "link_gmaps": "https://goo.gl/maps/example2"
  },
  "max_participants": 30,
  "max_volunteers": 5,
  "criteria_volunteers": "Mampu berkomunikasi dengan baik",
  "certificate_template": {
    "participant": "template_participant_3.pdf",
    "volunteer": "template_volunteer_3.pdf"
  },
  "payment_price": 100000,
  "payment_desc": "Pembayaran melalui aplikasi XYZ",
  "event_link": "",
  "is_volunteers": true,
  "is_certificate": true,
  "is_paid": true,
  "is_online": false
}

### edit data acara
PUT {{baseUrl}}/api/acara/Zx7J8JUOXWVRpfC2j5MZ
Content-Type: application/json

{
  "certificate_template": {
    "participant": "template_participant.png",
    "volunteer": ""
  }

}
### upload sertifikat data acara
PUT {{baseUrl}}/api/acara/upload-certificate/Zx7J8JUOXWVRpfC2j5MZ
Content-Type: application/json

{
  "participant": "template_participant.png"
}

### delete data acara
DELETE  {{baseUrl}}/api/acara/WfQ2cJHPzhsLkKIWIXDY
